### ISSUE TITLE
can't connect with https://db.mysite.com

### ISSUE THREAD

**Issue by seyed-dev** [ArangoDB-Community/aql-intellij-plugin#23] opened 2021-10-18 14:28 UTC
i can't connect with https://db.mysite.com with 443 port

**Comment by machak** [comment] 2021-11-26 18:14
fixed in #24 , plugin is uploaded,  pending Jetbrains review

**Comment by machak** [comment] 2021-11-26 18:14
duplicate of #24

**Closed** 2021-11-26 18:14 UTC
